services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: contract
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/contract
      JWT_SECRET_KEY: devsecret
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
      ADMIN_DEFAULT_EMAIL: admin@example.com
      ADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8000:8000"
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  db_data:
