name: Create Release with Artifacts

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Package artifacts
        run: bash scripts/package_release.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release_artifacts/frontend-dist.tar.gz
            release_artifacts/docs.tar.gz
            release_artifacts/docker-compose.prod.yml
            release_artifacts/.env.example
            release_artifacts/README.md
            release_artifacts/MANIFEST.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
